version: 8.2.x-{build}

image:
- Visual Studio 2015

environment:
  matrix:
  - TARGET: cmake
    CMAKE_CONFIG: Debug
    CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=OFF -Dbuild_tests=ON -Denable_cplusplus=ON -Denable_gc_assertions=ON -Werror=deprecated
  - TARGET: cmake
    CMAKE_CONFIG: Debug
    CMAKE_OPTIONS: -Dbuild_tests=ON -Denable_cplusplus=ON -Denable_gc_assertions=ON -Denable_gc_debug=ON -Denable_threads=OFF
  - TARGET: cmake
    CFLAGS_EXTRA: -DNO_MSGBOX_ON_ERROR -DNO_MPROTECT_VDB
    CMAKE_CONFIG: Release
    CMAKE_OPTIONS: -Dbuild_tests=ON -Denable_cplusplus=ON -Denable_large_config=ON -Ddisable_gc_debug=ON
  - TARGET: cmake
    CMAKE_CONFIG: Release
    CMAKE_OPTIONS: -Denable_parallel_mark=OFF
  - TARGET: nmake
    BLD: debug
    CPU: x86
    MACRO_DEFS: enable_static=1
    MS_SDK_VER: v7.1
  - TARGET: nmake
    BLD: debug
    CPU: x64
    MS_SDK_VER: v7.1
  - TARGET: nmake
    BLD: release
    CPU: x86
    MACRO_DEFS: nodebug=1
    MS_SDK_VER: v7.1
  - TARGET: cygwin
    CONF_OPTIONS: --enable-cplusplus
    CFLAGS_EXTRA: -D GCTEST_PRINT_VERBOSE
  - TARGET: cygwin
    CONF_OPTIONS: --enable-cplusplus --disable-munmap --enable-gc-assertions
  - TARGET: cygwin64
    CONF_OPTIONS: --enable-cplusplus
    CFLAGS_EXTRA: -D GCTEST_PRINT_VERBOSE
  - TARGET: cygwin64
    CFLAGS_EXTRA: -D GC_ALWAYS_MULTITHREADED -D LINT2 -D TEST_MANUAL_VDB
    CONF_OPTIONS: --enable-cplusplus --enable-gc-assertions --disable-shared
  - TARGET: cygwin64
    CONF_OPTIONS: --disable-threads
    CFLAGS_EXTRA: -std=c11 -D USE_WINALLOC
  - TARGET: mingw
    CFLAGS_EXTRA: -Werror -Wall -Wextra -Wpedantic
  - TARGET: mingw
    CFLAGS_EXTRA: -Werror -Wall -Wextra -Wpedantic -D GC_THREADS -D THREAD_LOCAL_ALLOC -D PARALLEL_MARK -D GC_ASSERTIONS -D EMPTY_GETENV_RESULTS -D GC_GCJ_SUPPORT -D USE_MUNMAP -D LARGE_CONFIG -D NO_MSGBOX_ON_ERROR
  - TARGET: mingw
    CFLAGS_EXTRA: -Werror -Wall -Wextra -Wpedantic -O3 -march=native -D GC_THREADS -D GC_GCJ_SUPPORT -D GC_TIME_LIMIT=10 -D WINXP_USE_PERF_COUNTER -D NO_MSGBOX_ON_ERROR
  - TARGET: mingw-shared-no-make
    CFLAGS_EXTRA: -Werror -Wall -Wextra -Wpedantic -D GC_THREADS -D GC_ASSERTIONS -D ENABLE_DISCLAIM -D GC_GCJ_SUPPORT -D GC_PREFER_MPROTECT_VDB -D GC_CALL=__stdcall -D GC_CALLBACK=__fastcall -D CONSOLE_LOG -D NO_MSGBOX_ON_ERROR
  - TARGET: mingw-w64
    CFLAGS_EXTRA: -Werror -Wall -Wextra -Wpedantic -D NO_MSGBOX_ON_ERROR
  - TARGET: mingw-w64
    CFLAGS_EXTRA: -Werror -Wall -Wextra -Wpedantic -D GC_THREADS -D THREAD_LOCAL_ALLOC -D PARALLEL_MARK -D GC_ASSERTIONS -D GC_GCJ_SUPPORT -D NO_RETRY_GET_THREAD_CONTEXT

clone_depth: 50

install:
- cmd: git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_8

build_script:
- cmd: if [%TARGET%]==[cmake] (
    cmake %CMAKE_OPTIONS% -Denable_werror=ON -DCFLAGS_EXTRA="%CFLAGS_EXTRA%" . && cmake --build . --config %CMAKE_CONFIG% )
- cmd: if [%TARGET%]==[nmake] (
    "C:\Program Files\Microsoft SDKs\Windows\%MS_SDK_VER%\Bin\SetEnv.cmd" /%CPU% /%BLD% && nmake /f NT_MAKEFILE %MACRO_DEFS% )
- cmd: if [%TARGET%]==[cygwin] (
    C:\cygwin\bin\bash -e -l -c
      "cd /cygdrive/c/projects/bdwgc && ./autogen.sh && ./configure %CONF_OPTIONS% --enable-werror && cat include/config.h && make -j CFLAGS_EXTRA='%CFLAGS_EXTRA%'" )
- cmd: if [%TARGET%]==[cygwin64] (
    C:\cygwin64\bin\bash -e -l -c
      "cd /cygdrive/c/projects/bdwgc && ./autogen.sh && ./configure %CONF_OPTIONS% --enable-werror && cat include/config.h && make -j CFLAGS_EXTRA='%CFLAGS_EXTRA%'" )
- cmd: if [%TARGET%]==[mingw] (
    C:\MinGW\msys\1.0\bin\bash -e -l -c
      "cd /c/projects/bdwgc && make -j -f Makefile.direct CC=gcc CFLAGS_EXTRA='%CFLAGS_EXTRA%'" )
- cmd: if [%TARGET%]==[mingw-shared-no-make] (
    C:\MinGW\msys\1.0\bin\bash -e -l -c
      "cd /c/projects/bdwgc && gcc -I include -D GC_BUILTIN_ATOMIC -D GC_DLL %CFLAGS_EXTRA% -shared -o gc.dll extra/gc.c" )
- cmd: if [%TARGET%]==[mingw-w64] (
    C:\msys64\usr\bin\bash -e -l -c
      "cd /c/projects/bdwgc && make -j -f Makefile.direct CC=gcc CFLAGS_EXTRA='%CFLAGS_EXTRA%'" )

test_script:
- cmd: if [%TARGET%]==[cmake] ( ctest --build-config %CMAKE_CONFIG% -V )
- cmd: if [%TARGET%]==[nmake] (
    "C:\Program Files\Microsoft SDKs\Windows\%MS_SDK_VER%\Bin\SetEnv.cmd" /%CPU% /%BLD% && nmake /f NT_MAKEFILE check %MACRO_DEFS% && nmake /f NT_MAKEFILE clean )
- cmd: if [%TARGET%]==[cygwin] (
    C:\cygwin\bin\bash -e -l -c
      "cd /cygdrive/c/projects/bdwgc && make -j check-without-test-driver CFLAGS_EXTRA='%CFLAGS_EXTRA%'" )
- cmd: if [%TARGET%]==[cygwin64] (
    C:\cygwin64\bin\bash -e -l -c
      "cd /cygdrive/c/projects/bdwgc && make -j check-without-test-driver CFLAGS_EXTRA='%CFLAGS_EXTRA%'" )
- cmd: if [%TARGET%]==[mingw] (
    C:\MinGW\msys\1.0\bin\bash -e -l -c
      "cd /c/projects/bdwgc && make -j -f Makefile.direct check CC=gcc CFLAGS_EXTRA='-DGC_NOT_DLL %CFLAGS_EXTRA%'" )
- cmd: if [%TARGET%]==[mingw-shared-no-make] (
    C:\MinGW\msys\1.0\bin\bash -e -l -c
      "cd /c/projects/bdwgc && gcc -I include -D GC_BUILTIN_ATOMIC -D GC_DLL %CFLAGS_EXTRA% -o gctest.exe tests/test.c gc.dll && gctest.exe" )
- cmd: if [%TARGET%]==[mingw-w64] (
    C:\msys64\usr\bin\bash -e -l -c
      "cd /c/projects/bdwgc && make -j -f Makefile.direct check CC=gcc CFLAGS_EXTRA='%CFLAGS_EXTRA%'" )
