version: 7.4.x-{build}

clone_depth: 50

build_script:
  - git clone --depth=50 https://github.com/ivmai/libatomic_ops.git -b release-7_4
  - cmake .
  - cmake --build . --config Debug

test_script:
  - ctest --build-config Debug -V
