# This workflow is for zig-based build/test running on Linux and MacOS (x64).
name: zig build

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.os }} thr:${{ matrix.enable_threads }} rwlock:${{ matrix.enable_rwlock }} redir:${{ matrix.redirect_malloc }} gcdeb:${{ matrix.enable_gc_debug }} munmap:${{ matrix.enable_munmap }} paramark:${{ matrix.parallel_mark }} thrlocal:${{ matrix.thread_local_alloc }} dll:${{ matrix.shared_libs }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 7

    strategy:
      fail-fast: false

      matrix:
        # TODO: move from nightly to zig 0.12 final when released.
        zig_version: [ "0.12.0-dev.2833+8802ec583" ]
        os: [ macos-latest, ubuntu-latest ]
        gc_assertions: [ true ]
        large_config: [ false ]
        enable_threads: [ false, true ]
        disable_handle_fork: [ false ]
        enable_rwlock: [ false, true ]
        redirect_malloc: [ false, true ]
        enable_gc_debug: [ false, true ]
        enable_munmap: [ false, true ]
        parallel_mark: [ false, true ]
        thread_local_alloc: [ false, true ]
        shared_libs: [ false, true ]
        exclude:
        - enable_threads: false
          disable_handle_fork: true
        - enable_threads: false
          parallel_mark: true
        - enable_threads: false
          enable_rwlock: true
        - enable_threads: false
          thread_local_alloc: true
        # The following ones are long-running jobs, thus excluded.
        - os: macos-latest
          enable_gc_debug: true
          enable_rwlock: true
        # The following ones just to reduce amount of jobs.
        - enable_munmap: false
          shared_libs: true
        - enable_munmap: true
          enable_threads: false
          shared_libs: false
        - enable_gc_debug: true
          enable_rwlock: true
          thread_local_alloc: false
        - parallel_mark: false
          redirect_malloc: true
        - enable_gc_debug: true
          thread_local_alloc: false
        - os: macos-latest
          enable_munmap: false
          enable_threads: false
        - os: macos-latest
          enable_munmap: false
          enable_rwlock: true
        - os: macos-latest
          enable_rwlock: true
          thread_local_alloc: false
        - os: macos-latest
          enable_rwlock: true
          parallel_mark: false
        - os: macos-latest
          enable_munmap: false
          redirect_malloc: false
        - os: macos-latest
          enable_threads: true
          redirect_malloc: false
          thread_local_alloc: false
        - os: macos-latest
          enable_threads: true
          parallel_mark: false
          redirect_malloc: false

    steps:
    - uses: actions/checkout@v4
    - name: "Install zig on Linux/x86_64"
      if: runner.os == 'Linux'
      run: |
        mkdir zig && curl https://ziglang.org/builds/zig-linux-x86_64-${{matrix.zig_version}}.tar.xz | tar Jx --directory=zig --strip-components=1
    - name: "Install zig on MacOS/x86_64"
      if: runner.os == 'macOS'
      run: |
        mkdir zig && curl https://ziglang.org/builds/zig-macos-x86_64-${{matrix.zig_version}}.tar.xz | tar Jx --directory=zig --strip-components=1
    - name: Build
      run: >
        zig/zig build
        -DBUILD_SHARED_LIBS=${{ matrix.shared_libs }}
        -Ddisable_handle_fork=${{ matrix.disable_handle_fork }}
        -Denable_gc_assertions=${{ matrix.gc_assertions }}
        -Denable_gc_debug=${{ matrix.enable_gc_debug }}
        -Denable_large_config=${{ matrix.large_config }}
        -Denable_munmap=${{ matrix.enable_munmap }}
        -Denable_parallel_mark=${{ matrix.parallel_mark }}
        -Denable_redirect_malloc=${{ matrix.redirect_malloc }}
        -Denable_rwlock=${{ matrix.enable_rwlock }}
        -Denable_thread_local_alloc=${{ matrix.thread_local_alloc }}
        -Denable_threads=${{ matrix.enable_threads }}
        -Denable_werror
        test
